import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloProvider } from "@apollo/client";
import client from "../apollo-client";
import { type PropsWithChildren } from "react";
import DefaultTheme from "./DefaultTheme";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps extends PropsWithChildren {}
export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <ApolloProvider client={client}>
          <DefaultTheme>{children}</DefaultTheme>
        </ApolloProvider>
      </body>
    </html>
  );
}
